version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myapp-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000"   # adapte si ton backend écoute autre port
    depends_on:
      - db  # si tu as une DB, sinon retire
    networks:
      - mynet
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myapp-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      VITE_API_URL: http://backend:3000  

    networks:
      - mynet

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet
    ports:
    - "5433:5432"   


volumes:
  db-data:

networks:
  mynet:
    driver: bridge
